# Generated by Django 3.0.4 on 2020-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_user',
            name='gender',
            field=models.CharField(default='', max_length=40),
        ),
    ]
